/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        consultas = (DefaultTableModel) this.jTable2.getModel();
        pacientes = (DefaultTableModel) this.jTable1.getModel();
        personal = (DefaultTableModel) this.jTable3.getModel();
        /**pruebas = (DefaultTableModel) this.jTable2.getModel();
        
        
        centros = (DefaultTableModel) this.jTable5.getModel();
        * */
    }

    DefaultTableModel consultas;
    DefaultTableModel pruebas;
    DefaultTableModel pacientes;
    DefaultTableModel personal;
    DefaultTableModel centros;

    sqlite_helper c1 = new sqlite_helper();

    private void actualizar() {
        try {
            Boolean resp = c1.Connect();
            if (resp) {
                ResultSet result = c1.Select("SELECT * FROM consulta", consultas);
                while (result.next()) {
                    consultas.addRow(new Object[]{result.getInt("id_consulta"), result.getString("fecha"), result.getString("fecha_sintomas"), result.getString("id_personal"), result.getString("id_prueba"), result.getString("id_paciente"), result.getString("id_triaje"), result.getString("id_diag")});
                }
                
                ResultSet result3 = c1.Select("SELECT * FROM paciente", pacientes);
                while (result3.next()) {
                    pacientes.addRow(new Object[]{result3.getInt("id_pac"), result3.getString("primer_nombre"), result3.getString("segundo_nombre"), result3.getString("primer_apellido"), result3.getString("segundo_apellido"), result3.getString("sexo"), result3.getString("fecha_nac")});
                }
                
                ResultSet result4 = c1.Select("SELECT * FROM personal", personal);
                while (result4.next()) {
                    personal.addRow(new Object[]{result4.getInt("id_personal"), result4.getString("primer_nombre"), result4.getString("segundo_nombre"), result4.getString("primer_apellido"), result4.getString("segundo_apellido"), result4.getString("sexo"), result4.getString("fecha_nac"), result4.getInt("id_triaje")});
                }
/**
                ResultSet result2 = c1.Select("SELECT * FROM prueba", pruebas);
                while (result2.next()) {
                    pruebas.addRow(new Object[]{result2.getInt("codigo_prueba"), result2.getString("tipo_prueba"), result2.getString("fecha_prueba"), result2.getString("resultado"), result2.getInt("id_paciente"), result2.getInt("codigo_personal")});
                }

                

                

                ResultSet result5 = c1.Select("SELECT * FROM centro_triaje", centros);
                while (result5.next()) {
                    centros.addRow(new Object[]{result5.getInt("codigo"), result5.getString("nombre"), result5.getString("horario")});
                }
**/
                c1.Disconnect();
            }
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, x.getMessage().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Fecha de los Sintomas", "ID Personal", "ID Prueba", "ID Paciente", "ID Triaje", "ID Diagnostico"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))))
        );

        jTabbedPane1.addTab("Consultas", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Paciente", "Nombre 1", "Nombre 2", "Apellido 1", "Apellido 2", "Sexo", "Fecha de Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paciente", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Personal", "Nombre 1", "Nombre 2", "Apellido 1", "Apellido 2", "Sexo", "Fecha de Nacimiento", "ID Triaje"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.actualizar();
    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = consultas.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String sql = "DELETE FROM consulta WHERE id_consulta = '" + id + "'";
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = consultas.getValueAt(0, 0).toString();
        String f1 = consultas.getValueAt(0, 1).toString();
        String f2 = consultas.getValueAt(0, 2).toString();
        String pe = consultas.getValueAt(0, 3).toString();
        String pru = consultas.getValueAt(0, 4).toString();
        String pa = consultas.getValueAt(0, 5).toString();
        String tri = consultas.getValueAt(0, 6).toString();
        String diag = consultas.getValueAt(0, 7).toString();
        String sql = "INSERT INTO consulta(id_consulta,fecha, fecha_sintomas, id_personal, id_prueba, id_paciente, id_triaje, id_diag)VALUES('" +  id + "','" +  f1 + "','" +  f2 + "','"+  pe + "','"+  pru + "','"+  pa + "','"+  tri + "','"+  diag + "')";
        
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = pacientes.getValueAt(0, 0).toString();
        String v1 = pacientes.getValueAt(0, 1).toString();
        String v2 = pacientes.getValueAt(0, 2).toString();
        String v3 = pacientes.getValueAt(0, 3).toString();
        String v4 = pacientes.getValueAt(0, 4).toString();
        String v5 = pacientes.getValueAt(0, 5).toString();
        String v6 = pacientes.getValueAt(0, 6).toString();
        
        String sql = "INSERT INTO paciente(id_pac,primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, sexo, fecha_nac)VALUES('" +  id + "','" +  v1 + "','" +  v2 + "','"+  v3 + "','"+ v4 + "','"+  v5 + "','"+  v6  + "')";
        
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = pacientes.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String sql = "DELETE FROM paciente WHERE id_pac = '" + id + "'";
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id = personal.getValueAt(0, 0).toString();
        String v1 = personal.getValueAt(0, 1).toString();
        String v2 = personal.getValueAt(0, 2).toString();
        String v3 = personal.getValueAt(0, 3).toString();
        String v4 = personal.getValueAt(0, 4).toString();
        String v5 = personal.getValueAt(0, 5).toString();
        String v6 = personal.getValueAt(0, 6).toString();
        String v7 = personal.getValueAt(0, 6).toString();

        String sql = "INSERT INTO personal(id_personal,primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, sexo, fecha_nac, id_triaje)VALUES('" +  id + "','" +  v1 + "','" +  v2 + "','"+  v3 + "','"+ v4 + "','"+  v5 + "','"+  v6 + "','" + v7 + "')";
        
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id = personal.getValueAt(jTable3.getSelectedRow(), 0).toString();
        String sql = "DELETE FROM personal WHERE id_personal = '" + id + "'";
        c1.Connect();
        c1.ExQ(sql);
        c1.Disconnect();
        this.actualizar();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
